### ISSUE TITLE
item di xml navigation bar tidak dikenali di order activity

### ISSUE THREAD

**Issue by ghost** [pplnostrateam/insantani-frontend#38]
ketika memanggil misalnya R.id.button dari order.java maka returnnya selalu null

**Comment by harticocaesario** [comment]
Coba pakai cara ini (untuk textView) :
navHeaderView= navigationView.inflateHeaderView(R.layout.nav_header_order);
userName= (TextView) navHeaderView.findViewById(R.id.user_name_nav);

**Comment by pplnostrateam** [comment]
solved.
